### PR TITLE
Fix truffleruby test failure

### PR DESCRIPTION
**Pull request by stanhu**
ruby_types -> magic_ruby_types

### CODE REVIEW

**Review by kwilczynski — APPROVED** [review]
Hi @stanhu, thank you for fixinging!

Doh! A brown bag moment for me.

**Comment by stanhu** [comment]
Hmm, it's still failing: https://travis-ci.com/github/kwilczynski/ruby-magic/jobs/500000739

**Comment by kwilczynski** [comment]
Hi @stanhu,

> Hmm, it's still failing: https://travis-ci.com/github/kwilczynski/ruby-magic/jobs/500000739

We've seen this before, the encoding-related crash.

Let me see what I can do about this.

Krzysztof

**Comment by kwilczynski** [comment]
Hi,

Oh bugger. I though, I could just enable debug to see what is going on, but no... you need to request it from Travis CI as per:

[running-build-in-debug-mode/#enabling-debug-mode](https://docs.travis-ci.com/user/running-build-in-debug-mode/#enabling-debug-mode)

Well, let me do it. Might take a while.

Krzysztof

**Comment by stanhu** [comment]
I also see this failure in GitLab CI: https://gitlab.com/stanhu/ruby-magic/-/jobs/1197317644

**Comment by kwilczynski** [comment]
Hi @stanhu,

> I also see this failure in GitLab CI: https://gitlab.com/stanhu/ruby-magic/-/jobs/1197317644

I see. Let me check this locally, but at the first glance it looks like TruffleRuby outputs different format of when you use the `rb_warn()` function.

Krzysztof

**Comment by kwilczynski** [comment]
Hi @stanhu,

The commit https://github.com/kwilczynski/ruby-magic/commit/1093895642960628e87b1cfef80df3c3befbdaf0 should hopefully address this issue.

Also, paging @eregon, as this seem like another difference Ruby vs TruffleRuby that might be worth looking into.

Krzysztof

**Comment by kwilczynski** [comment]
Hi @eregon, any comment on the output difference?

Should I open an issue regarding this?

Krzysztof

**Comment by eregon** [comment]
@kwilczynski Yes, an issue on the truffleruby repo would be best, it seems TruffleRuby is missing a `warning: ` prefix? Is it for rb_warn() or so?

**Pull request merged**
